### ISSUE TITLE
Warnings (node version)

### ISSUE THREAD

**Issue by ViolanteCodes** [ButterCMS/react-starter-buttercms#3]
I'm seeing a lot of warnings with NPM install - I'm guessing because we didn't specify the exact node version, and I'm running a different version locally. Can we specify node version with the package (I feel like we did this for gatsby?)

**Comment by ViolanteCodes** [comment]
> @ViolanteCodes What's your node version on what you have these errors? (run `node -v`)
> 
> My version:
> 
> ```
> ➜  react-starter-buttercms git:(feature/smooth-scroll-navbar) node -v
> v16.13.2
> ```
> 
> I added `.nvmrc` file to automatically choose node version while using [nvm](https://github.com/nvm-sh/nvm). Do you want to add a strict engine lock in package.json? I would suggest having just the `.nvmrc` file to be able to run it also in different node versions but yes, you'll see these warnings then but it doesn't block users in using the starter projects while setting strict engine will block them and don't allow run it.

Okay, no, that make sense - can we maybe just add a badge with the suggested node version to make it more visible?

**Comment by prokopsimek** [comment]
@ViolanteCodes Check the badge at beginning of readme. https://github.com/ButterCMS/react-starter-buttercms Is that ok now?

**Comment by ViolanteCodes** [comment]
LGTM, closing issue.
